apiVersion: v1
kind: Service
metadata:
  name: loadgenrator
  namespace: jenkins
spec:
  selector:
    app: loadgenrator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP